#version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5430:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: sys
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sys"]
      interval: 10s
      timeout: 5s
      retries: 5

  angular:
    build:
      context: ./ClientApp
    container_name: angular-container
    volumes:
      - ./ClientApp/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4200:80"
    networks:
      - app-network

  laravel:
    build:
      context: ./ServerApp
    container_name: laravel-container
    ports:
      - "8000:8000"
    volumes:
      - ./ServerApp:/var/www
    networks:
      - app-network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:your_app_key
    depends_on:
      - postgres

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
